In [1]:
import numpy as np

from mdctn.core import mdct, imdct

In [2]:
x = np.arange(24)

In [3]:
a1 = x[0:4]
a2 = x[4:8]
b1 = x[8:12]
b2 = x[12:16]
c1 = x[16:20]
c2 = x[20:24]

In [4]:
x1 = np.hstack([c2, a1, a2, b1])
x2 = np.hstack([a2, b1, b2, c1])
x3 = np.hstack([b2, c1, c2, a1])

y1 = mdct(x1)
y2 = mdct(x2)
y3 = mdct(x3)

print(y1, y2, y3)

In [5]:
z1 = imdct(y1)
z2 = imdct(y2)
z3 = imdct(y3)

In [6]:
print(z1[8:16] + z2[0:8]) # a2, b1
print(z2[8:16] + z3[0:8]) # b2, c1
print(z3[8:16] + z1[0:8]) # c2, a1

[ 4.  5.  6.  7.  8.  9. 10. 11.]
[12. 13. 14. 15. 16. 17. 18. 19.]
[20. 21. 22. 23.  0.  1.  2.  3.]
