In [1]:
import numpy as np

from scipy.signal.windows import kaiser_bessel_derived
from scipy.fft import dct, idct

In [8]:
def mdct(x):
    N = x.shape[0]

    if N%4 != 0:
        raise ValueError("MDCT is only defined for vectors lengths multiple of four.")

    N4 = N // 4

    a = x[0*N4:1*N4]
    b = x[1*N4:2*N4]
    c = x[2*N4:3*N4]
    d = x[3*N4:4*N4]

    br = np.flip(b)
    cr = np.flip(c)

    return dct(np.hstack([-cr - d, a - br]), norm='ortho')

def imdct(y):
    N = y.shape[0] * 2

    if N%4 != 0:
        raise ValueError("IMDCT is only defined for vectors lengths multiple of two.")
    
    z = idct(y, norm='ortho')

    z = np.hstack([z, -np.flip(z), -z])

    # return z[N//2:5*N//2]
    return z[:2*N]


In [10]:
X = np.arange(32)
Y1 = mdct(X[0:16])
Y2 = mdct(X[8:24])
Z1 = imdct(Y1)
Z2 = imdct(Y2)
print(Z1[8:16]+ Z2[:8] - 2*X[8:16]) # should be about 0
print(Z1[8:16] + Z2[:8])
print(X[8:16])

[-54. -54. -54. -54.  -8.  -8.  -8.  -8.]
[-38. -36. -34. -32.  16.  18.  20.  22.]
[ 8  9 10 11 12 13 14 15]


In [12]:
X = np.arange(1000)
Y1 = mdct(X[:100] * kaiser_bessel_derived(100, beta=16))
Y2 = mdct(X[50:150] * kaiser_bessel_derived(100, beta=16))
Z1 = imdct(Y1) * kaiser_bessel_derived(100, beta=16)
Z2 = imdct(Y2) * kaiser_bessel_derived(100, beta=16)
print(Z1[50:100] + Z2[:50] - 2*X[50:100]) # should be about 0

ValueError: operands could not be broadcast together with shapes (150,) (100,) 

In [ ]:
X = np.random.rand(1000)

y = dct(X, norm='ortho')

(X - idct(y, norm='ortho')).max()

In [ ]:
X