In [1]:
import tensorflow as tf
import numpy as np

2022-12-20 10:10:05.605507: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
# x = np.hstack([np.zeros(16), np.arange(64, dtype=np.float64), np.zeros(16)])

# x = np.arange(64, dtype=np.float64)

x = np.asarray([ 
    137, 154, 127, 107, 134, 148, 171, 228, 
    35,  199, 141, 238,  94, 179, 201,  90,
    213, 176, 226, 219, 212,  47, 250,  93,
    227, 226,  34, 220,  95,  36,  37, 162,
    184,  44,  94,  44, 182, 173,  39, 159,
     67,  98,  81, 122,  44, 104,  89, 184,
    178, 147, 225,  39, 176, 212, 113,  84,
    213, 243, 193,  56, 183,   2,  69, 212,
], dtype=np.float64)

x = x - 128

In [3]:
x

array([   9.,   26.,   -1.,  -21.,    6.,   20.,   43.,  100.,  -93.,
         71.,   13.,  110.,  -34.,   51.,   73.,  -38.,   85.,   48.,
         98.,   91.,   84.,  -81.,  122.,  -35.,   99.,   98.,  -94.,
         92.,  -33.,  -92.,  -91.,   34.,   56.,  -84.,  -34.,  -84.,
         54.,   45.,  -89.,   31.,  -61.,  -30.,  -47.,   -6.,  -84.,
        -24.,  -39.,   56.,   50.,   19.,   97.,  -89.,   48.,   84.,
        -15.,  -44.,   85.,  115.,   65.,  -72.,   55., -126.,  -59.,
         84.])

In [4]:
y = tf.signal.mdct(x, frame_length=16, window_fn=tf.signal.kaiser_bessel_derived_window, norm='ortho')

2022-12-20 10:10:11.515521: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-12-20 10:10:11.516601: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.


In [5]:
npy = np.asmatrix(y).copy()

npy[:, -5:] = 0

print(npy)

[[ -91.17325552    5.95912597  -59.44605531    0.            0.
     0.            0.            0.        ]
 [-159.18892175  -43.09642208  -22.04861674    0.            0.
     0.            0.            0.        ]
 [ -52.3436991    33.19353794   69.05743597    0.            0.
     0.            0.            0.        ]
 [  72.45991301  -27.46428235   94.80221117    0.            0.
     0.            0.            0.        ]
 [  86.5187079    35.94166976  -33.84868868    0.            0.
     0.            0.            0.        ]
 [ -65.00135625  -10.79116069   84.90579507    0.            0.
     0.            0.            0.        ]
 [ -74.00373959   25.44075615   45.56727704    0.            0.
     0.            0.            0.        ]]


In [6]:
z = tf.signal.inverse_mdct(npy, window_fn=tf.signal.kaiser_bessel_derived_window, norm='ortho')

print(z)

tf.Tensor(
[ -0.09840071  -3.7384241  -12.98066399 -11.03419291  15.8889097
  43.20853057  43.14904692  22.91923973   8.07879742  14.88104139
  37.74717024  52.60531916  44.74213689  29.52833187  24.44558055
  28.32512409  40.64245486  62.94832487  91.08289513  95.05682591
  55.18515344  12.81206679  12.42925179  41.4383201   61.1877336
  53.21550057  30.31334925   0.38110717 -36.11640182 -62.21398037
 -56.43289213 -21.072389    10.9513799    5.30277059 -34.54016771
 -58.26536773 -29.56081689   8.60297513   8.71892972 -16.46059389
 -41.2847478  -51.33198294 -38.33483844 -26.73466751 -40.95909311
 -50.13430423 -21.49172385  28.00616973  63.02687292  60.42633178
  29.68330689   2.00651757  -2.77131472   6.72485012  20.94184401
  41.57682896  56.40123974  48.81504011  24.04409809   3.74351428
   2.59971637   7.22330415   4.22932452   0.24215122], shape=(64,), dtype=float64)


In [7]:
px = np.reshape(x, (8, 8))
pz = np.asarray(z).reshape((8, 8)).copy()
for i in range(8):
    print(f'-----{i}-----')
    print(px[i, :] + 125)
    print(pz[i, :] + 125)


-----0-----
[134. 151. 124. 104. 131. 145. 168. 225.]
[124.90159929 121.2615759  112.01933601 113.96580709 140.8889097
 168.20853057 168.14904692 147.91923973]
-----1-----
[ 32. 196. 138. 235.  91. 176. 198.  87.]
[133.07879742 139.88104139 162.74717024 177.60531916 169.74213689
 154.52833187 149.44558055 153.32512409]
-----2-----
[210. 173. 223. 216. 209.  44. 247.  90.]
[165.64245486 187.94832487 216.08289513 220.05682591 180.18515344
 137.81206679 137.42925179 166.4383201 ]
-----3-----
[224. 223.  31. 217.  92.  33.  34. 159.]
[186.1877336  178.21550057 155.31334925 125.38110717  88.88359818
  62.78601963  68.56710787 103.927611  ]
-----4-----
[181.  41.  91.  41. 179. 170.  36. 156.]
[135.9513799  130.30277059  90.45983229  66.73463227  95.43918311
 133.60297513 133.71892972 108.53940611]
-----5-----
[ 64.  95.  78. 119.  41. 101.  86. 181.]
[ 83.7152522   73.66801706  86.66516156  98.26533249  84.04090689
  74.86569577 103.50827615 153.00616973]
-----6-----
[175. 144. 222.  36. 17

In [8]:
px += 125
pz += 125

In [9]:
px

array([[134., 151., 124., 104., 131., 145., 168., 225.],
       [ 32., 196., 138., 235.,  91., 176., 198.,  87.],
       [210., 173., 223., 216., 209.,  44., 247.,  90.],
       [224., 223.,  31., 217.,  92.,  33.,  34., 159.],
       [181.,  41.,  91.,  41., 179., 170.,  36., 156.],
       [ 64.,  95.,  78., 119.,  41., 101.,  86., 181.],
       [175., 144., 222.,  36., 173., 209., 110.,  81.],
       [210., 240., 190.,  53., 180.,  -1.,  66., 209.]])

In [12]:
pz

array([[124.90159929, 121.2615759 , 112.01933601, 113.96580709,
        140.8889097 , 168.20853057, 168.14904692, 147.91923973],
       [133.07879742, 139.88104139, 162.74717024, 177.60531916,
        169.74213689, 154.52833187, 149.44558055, 153.32512409],
       [165.64245486, 187.94832487, 216.08289513, 220.05682591,
        180.18515344, 137.81206679, 137.42925179, 166.4383201 ],
       [186.1877336 , 178.21550057, 155.31334925, 125.38110717,
         88.88359818,  62.78601963,  68.56710787, 103.927611  ],
       [135.9513799 , 130.30277059,  90.45983229,  66.73463227,
         95.43918311, 133.60297513, 133.71892972, 108.53940611],
       [ 83.7152522 ,  73.66801706,  86.66516156,  98.26533249,
         84.04090689,  74.86569577, 103.50827615, 153.00616973],
       [188.02687292, 185.42633178, 154.68330689, 127.00651757,
        122.22868528, 131.72485012, 145.94184401, 166.57682896],
       [181.40123974, 173.81504011, 149.04409809, 128.74351428,
        127.59971637, 132.2233041

In [19]:
px

array([[134., 151., 124., 104., 131., 145., 168., 225.],
       [ 32., 196., 138., 235.,  91., 176., 198.,  87.],
       [210., 173., 223., 216., 209.,  44., 247.,  90.],
       [224., 223.,  31., 217.,  92.,  33.,  34., 159.],
       [181.,  41.,  91.,  41., 179., 170.,  36., 156.],
       [ 64.,  95.,  78., 119.,  41., 101.,  86., 181.],
       [175., 144., 222.,  36., 173., 209., 110.,  81.],
       [210., 240., 190.,  53., 180.,  -1.,  66., 209.]])

In [20]:
np.abs(pz - px)

array([[  9.09840071,  29.7384241 ,  11.98066399,   9.96580709,
          9.8889097 ,  23.20853057,   0.14904692,  77.08076027],
       [101.07879742,  56.11895861,  24.74717024,  57.39468084,
         78.74213689,  21.47166813,  48.55441945,  66.32512409],
       [ 44.35754514,  14.94832487,   6.91710487,   4.05682591,
         28.81484656,  93.81206679, 109.57074821,  76.4383201 ],
       [ 37.8122664 ,  44.78449943, 124.31334925,  91.61889283,
          3.11640182,  29.78601963,  34.56710787,  55.072389  ],
       [ 45.0486201 ,  89.30277059,   0.54016771,  25.73463227,
         83.56081689,  36.39702487,  97.71892972,  47.46059389],
       [ 19.7152522 ,  21.33198294,   8.66516156,  20.73466751,
         43.04090689,  26.13430423,  17.50827615,  27.99383027],
       [ 13.02687292,  41.42633178,  67.31669311,  91.00651757,
         50.77131472,  77.27514988,  35.94184401,  85.57682896],
       [ 28.59876026,  66.18495989,  40.95590191,  75.74351428,
         52.40028363, 133.2233041

In [21]:
np.abs(pz - px) / px

array([[ 6.78985127e-02,  1.96943206e-01,  9.66182580e-02,
         9.58250682e-02,  7.54878603e-02,  1.60058832e-01,
         8.87184058e-04,  3.42581157e-01],
       [ 3.15871242e+00,  2.86321217e-01,  1.79327321e-01,
         2.44232684e-01,  8.65298208e-01,  1.21998114e-01,
         2.45224341e-01,  7.62357748e-01],
       [ 2.11226405e-01,  8.64065021e-02,  3.10184075e-02,
         1.87816014e-02,  1.37870079e-01,  2.13209243e+00,
         4.43606268e-01,  8.49314668e-01],
       [ 1.68804761e-01,  2.00827352e-01,  4.01010804e+00,
         4.22206879e-01,  3.38739329e-02,  9.02606655e-01,
         1.01667964e+00,  3.46367226e-01],
       [ 2.48887404e-01,  2.17811636e+00,  5.93590895e-03,
         6.27673958e-01,  4.66820206e-01,  2.14100146e-01,
         2.71441471e+00,  3.04234576e-01],
       [ 3.08050816e-01,  2.24547189e-01,  1.11091815e-01,
         1.74240903e-01,  1.04977822e+00,  2.58755487e-01,
         2.03584606e-01,  1.54662046e-01],
       [ 7.44392738e-02,  2.876828

In [5]:
npy = np.asmatrix(y).copy()

In [6]:
npy

matrix([[ -91.17325552,    5.95912597,  -59.44605531,  -21.30247023,
           60.19704551,   24.49864982, -106.70117295,  -68.87281857],
        [-159.18892175,  -43.09642208,  -22.04861674,   -6.84652334,
           12.88954796, -110.55290531,   81.13359135,   -5.40820057],
        [ -52.3436991 ,   33.19353794,   69.05743597,  -51.95450947,
          -32.90576897, -163.78745554,  -93.36076914,  115.14754805],
        [  72.45991301,  -27.46428235,   94.80221117,  -90.82001031,
          -38.35594451,   42.35097404,   83.83108712,  -28.70113895],
        [  86.5187079 ,   35.94166976,  -33.84868868,   44.34956516,
          -66.2995675 ,   90.26818553,  -53.27594014,  -43.56037831],
        [ -65.00135625,  -10.79116069,   84.90579507,    3.55704087,
           56.87862169,   68.68983551,   81.96229849,  -34.96194804],
        [ -74.00373959,   25.44075615,   45.56727704,  141.24243086,
          -63.65735187,   -5.18337396,  -18.01075996,   35.92245802]])