In [66]:
import numpy as np

In [67]:
def window_maker(x, skip=8):
    npx = np.asarray(x, dtype=np.float64)

    npx = npx.reshape(npx.shape[0] // skip, skip)

    return np.hstack([npx[:-1], npx[1:]])

In [68]:
def mdct(x):
    npx = np.asarray(x, dtype=np.float64)

    N = int(npx.shape[0])

    N2 = N // 2
    N4 = N // 4

    X = np.zeros(N2, dtype=np.float64)

    for i in range(N2):
        sigma = 0
        for j in range(N):
            sigma += npx[j] * np.cos((np.pi/N2) * (j + 0.5 + N4) * (i + 0.5))
        
        X[i] = sigma
    
    return X

In [69]:
def imdct(X):
    npX = np.asarray(X, dtype=np.float64)

    N = int(npX.shape[0] * 2)

    N2 = N // 2
    N4 = N // 4

    x = np.zeros(N, dtype=np.float64)

    for j in range(N):
        sigma = 0
        for i in range(N2):
            sigma += npX[i] * np.cos((np.pi/N2) * (j + 0.5 + N4) * (i + 0.5))
   
        x[j] = sigma / N2
    
    return x

In [70]:
x = np.arange(32)

xw = window_maker(x)

Xw = [mdct(w) for w in xw]

yw = [imdct(w) for w in Xw]

In [71]:
yw[0][8:] + yw[1][:8]

array([ 8.,  9., 10., 11., 12., 13., 14., 15.])

In [72]:
yw

[array([-3.5, -2.5, -1.5, -0.5,  0.5,  1.5,  2.5,  3.5, 11.5, 11.5, 11.5,
        11.5, 11.5, 11.5, 11.5, 11.5]),
 array([-3.5, -2.5, -1.5, -0.5,  0.5,  1.5,  2.5,  3.5, 19.5, 19.5, 19.5,
        19.5, 19.5, 19.5, 19.5, 19.5]),
 array([-3.5, -2.5, -1.5, -0.5,  0.5,  1.5,  2.5,  3.5, 27.5, 27.5, 27.5,
        27.5, 27.5, 27.5, 27.5, 27.5])]

In [73]:
xw

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
        13., 14., 15.],
       [ 8.,  9., 10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20.,
        21., 22., 23.],
       [16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26., 27., 28.,
        29., 30., 31.]])

In [74]:
Xw

[array([-90.72891379, -14.25425402,  12.65336024,   7.68055862,
         -7.2359366 ,  -5.79906942,   5.65400987,   5.29397081]),
 array([-148.44182227,  -33.74151839,   24.6535584 ,   16.59751028,
         -14.5538897 ,  -12.21330896,   11.56540689,   10.97819615]),
 array([-206.15473075,  -53.22878277,   36.65375655,   25.51446194,
         -21.87184281,  -18.62754851,   17.47680392,   16.6624215 ])]