In [1]:
import numpy as np

In [2]:
def lsrgb_to_oklab_old(r, g, b):

    l = np.cbrt(0.4122214708 * r + 0.5363325363 * g + 0.0514459929 * b)
    m = np.cbrt(0.2119034982 * r + 0.6806995451 * g + 0.1073969566 * b)
    s = np.cbrt(0.0883024619 * r + 0.2817188376 * g + 0.6299787005 * b)

    # return (l, m, s)

    l_ = 0.2104542553 * l + 0.7936177850 * m - 0.0040720468 * s
    m_ = 1.9779984951 * l - 2.4285922050 * m + 0.4505937099 * s
    s_ = 0.0259040371 * l + 0.7827717662 * m - 0.8086757660 * s

    return (l_, m_, s_)

def lsrgb_to_oklab(r, g, b):
    rgb = np.zeros((r.size, 3))

    rgb[:, 0] = r.ravel()
    rgb[:, 1] = g.ravel()
    rgb[:, 2] = b.ravel()

    m1 = np.matrix([
        [0.4122214708, 0.5363325363, 0.0514459929],
        [0.2119034982, 0.6806995451, 0.1073969566],
        [0.0883024619, 0.2817188376, 0.6299787005],
    ])

    lms = np.inner(m1, rgb).T

    lms = np.cbrt(lms)

    m2 = np.matrix([
        [0.2104542553, +0.7936177850, -0.0040720468],
        [1.9779984951, -2.4285922050, +0.4505937099],
        [0.0259040371, +0.7827717662, -0.8086757660],
    ])

    lms_ = np.inner(m2, lms).T

    l_ = lms_[:, 0].reshape(r.shape)
    m_ = lms_[:, 1].reshape(r.shape)
    s_ = lms_[:, 2].reshape(r.shape)

    return (l_, m_, s_)

In [3]:
r = np.array([10, 50])
g = np.array([20, 60])
b = np.array([30, 70])

In [4]:
lsrgb_to_oklab_old(r, g, b)

(array([2.63865299, 3.87940142]),
 array([-0.12586111, -0.05133782]),
 array([-0.22474958, -0.11251011]))

In [5]:
lsrgb_to_oklab(r, g, b)

(matrix([[2.63865299, 3.87940142]]),
 matrix([[-0.12586111, -0.05133782]]),
 matrix([[-0.22474958, -0.11251011]]))